// ============================================================
// Gambar contoh untuk `npm run seed:demo`.
//
// Bukan foto orang sungguhan -- hanya siluet berwarna, supaya galeri
// dan riwayat terlihat berisi saat aplikasi diperagakan. Sengaja
// ditanam sebagai base64 (masing-masing di bawah 2 KB) supaya seed
// demo tidak butuh koneksi internet atau paket gambar tambahan.
//
// Tidak pernah dipakai di jalur produksi: hanya seed-demo.js yang
// memanggil berkas ini.
// ============================================================

const GAMBAR = [
  [
    '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABh',
    'Y3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAAB',
    'UAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAA',
    'AAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9Y',
    'WVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAM',
    'ZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAwICQsJCAwLCgsODQwOEh4UEhEREiUbHBYe',
    'LCcuLisnKyoxN0Y7MTRCNCorPVM+QkhKTk9OLztWXFVMW0ZNTkv/2wBDAQ0ODhIQEiQUFCRLMisyS0tLS0tLS0tLS0tLS0tLS0tL',
    'S0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0v/wAARCADwAPADASIAAhEBAxEB/8QAGgABAQEBAQEBAAAAAAAAAAAAAAEE',
    'AwUCBv/EACsQAQACAQIEBQMFAQAAAAAAAAABAgMEERIhMVEyQWFxgSKRsRQjM1KhQv/EABgBAQEBAQEAAAAAAAAAAAAAAAABAgME',
    '/8QAGhEBAQEBAQEBAAAAAAAAAAAAAAERMRIhAv/aAAwDAQACEQMRAD8A/QCD3POogCiAKIAogCiAKIAogCiAKIAogCiAKIAogCiA',
    'IIAogCiAKIAogCiAKIAogCiAKIAogCiAKIAogCiAIIAogCiAKIAogCiAKIAogCiAKIAogCiAKIAogCiAIIAogCiAKIAogCiAKOmP',
    'Ba/OeUO9cNK+W/ummMg3xER0iIJiJ6xCelxgGu2GlvLb2cMmC1Occ4XUxzEFFEAUQBRAFEAUQBBAFEAUQBRAFEAVpwYeUWtHtDlp',
    '6cd956Q2M2rFEGVUQBRAHDPh5Tase8Mz0GPUU4L7x0lqVK5iDSKIAogCiAKIAggIogCiAKIAogDdp68OKPXm6JWNqxHaFYbAEAAA',
    'ABz1FeLFPpzdEtG9Zj0UeeINsKIAogCiAKIAggCiAKIAogCiAPSrO9YnvCuWntxYo9OTow2oggogCiAKlp2rM9oHLU24cU955KMY',
    'g2wogCiAKIAogCCAKIAogCiAKIA7abJwX2npLa8xp0+eNopefaWbGpWsQZVRAFEAGLU5OO+0dIfeozxtNKT7yzNSM2qINIogCiAK',
    'IAogCCAKIAogCiAKIAogDti1Fqcp+qvq001GO3nt7sAmLr04tWekxPyTasdZiPl5gnldb7ajHXz39mbLqLX5R9NXEXE1RBUUQBRA',
    'FEAUQBRAEEAUQBRAFEAUQBRAFEfUY726Vn7Ag+/0+X+v+n6fL/X/AE1XwLOO9etZ+z5EUQBRAFEAUQBRAFEAQQBRAFEAUQBRGrDp',
    'ulsn2NVxx475J+mPlpppKx4539Id42iNo5QM6uJWlaeGsQ+kEVRBBXzalb+KsSoo4X0lZ8E7eks2THfHP1R8vQJ2mNp5wsqY8wac',
    '2m/6x/Zla1FEBFEAUQBRAEEAUQBRAFEatHi3/ctHsX4rpp8HBHFbxfh3BhoAQAAAAAAAAHDUYOOOKvi/LuKPLGnWYtv3Kx7src+s',
    'qICKIAogCCCiiAKIA+8dZveKx5y9KsRWIiOkMehrva1u0bNjFaiiDKqIAogCiAKIAogCiAFoi0TE9JebkrNLzWfKXpMeurtatu/J',
    'r8pWcQbZUQBRAEEAUQBRAG/RRth37y7uOk/gr8/l2c71oARQAAAAAAAAAAABw1sb4d+0u7jq/wCC3x+VnUYBB0ZUQBRAEEAUQBRA',
    'G/RW3w7dpaGLQX2taveN2xzvWoogiqIAogCiAKIAogCiAKz6222HbvLux66+9q17Rus6lZhB0ZUQBRAH/9k=',
  ].join(``),
  [
    '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABh',
    'Y3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAAB',
    'UAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAA',
    'AAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9Y',
    'WVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAM',
    'ZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAwICQsJCAwLCgsODQwOEh4UEhEREiUbHBYe',
    'LCcuLisnKyoxN0Y7MTRCNCorPVM+QkhKTk9OLztWXFVMW0ZNTkv/2wBDAQ0ODhIQEiQUFCRLMisyS0tLS0tLS0tLS0tLS0tLS0tL',
    'S0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0v/wAARCADwAPADASIAAhEBAxEB/8QAGgABAQEBAQEBAAAAAAAAAAAAAAEC',
    'BAMFBv/EACsQAQACAgAEBQIHAQAAAAAAAAABEQIDBBIhMTJRYXGBQZETIjNCUqGxI//EABcBAQEBAQAAAAAAAAAAAAAAAAABAgT/',
    'xAAWEQEBAQAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/AP1NlpZbLmWy0ssFstLLBbLSywWy0ssFstLLBbLSywWy0ssFstLL',
    'BbLSywWy0ssFstLLBbLSywWy0ssFstLLBLLQRFstAFstAFstAFstAFstAFstAFstAFstAFstAFstAFstAFstAFstAFstAGRBRRAF',
    'EAUQBRAFEAUQBRAFEAUQBRAFEAUQBRAFEAQQBRAFEAUQBRAFEAUbw05ZdZ6Q98dWGP0v3FxyjtiIjtEExE94gMcQ6stWGX0r2eOe',
    'nLHrHWAx5iAiiAKIAogCiAKIAgllgollgollgollgollgro06ukZZR7Q8tGHPnc9odYsgANAAAAPHdq6c2PzDndzk34cmdx2kZsY',
    'EssRRLLBRLLBRLLBRLLBLLZssGrLZssGrLZssGrLZssGrLZssHbojl1x69Xozj0xiPRRpRAVRAFEAV5745tc+nVtMuuMx6COKy2b',
    'LGWrLZssGrLZssGrLZssGrLZssEEBFEAUQBRAFEAfQxm8Yn0V5aMubVHp0eg2ogCiAKIAqZTWMz6Dz4jLl1T69AcggMKIAogCiAK',
    'IAggCiAKIAogCiAPbh9nJnU9pdj5ro0b4qMc59pFldQyDTQyA0MgNOPiNnPnUdoa374rlwn3lzjNqiAiiAKIAogCiAIIAogCiAKI',
    'AogCiAPbXvyw6T1h7479eX1r3cQLr6MZYz2mJ+ScsY7zEfL5wGu3Lfrx+t+zw2b8s+kdIeIGqICKIAogCiAKIAogDIgCiAKIAogC',
    'iAKIAojUYZz2xn7Ag3+Bs/j/AGfgbP4/2DAs4Zx3xn7MgogCiAKIAogCiAKIAggIogCiAKIAojp08N+7Z9hXjr15bJ/LHy6cOFxj',
    'xzfs9o6RUA1hjhjj4cYhUBVEAVMsMcvFjEgDxz4XGfBNe7mz15a5/NHy7yesVImPnDo3cN+7X9nMMqICKIAogCiAMiAKIAogCqy6',
    'uE1fvy+BXpw+nkjmy8X+PdAaUQBRAFEAUQBRAFeHEaeeObHxf69gHzUdPF6q/wCmPy5RlRARRAFEAQQBRAFEAb148+cYx9X0YiMY',
    'iI7Q5OCxvLLLy6OsaiiAqiAKIAogCiAKIAogBMRlExPaXzs8eTOcZ+j6Lk43GsscvPoJXOIDKiAKIAggCiAKIA7uDitV+cvd48L+',
    'hj8vYbgAAAAAAAAAAAAAA8OMi9V+Uvd48V+hl8BXCIDCiAKIAlls2WDVls2WDVls2WDv4PK9NeUuhxcDnWWWPn1dg1FEBVEAUQBR',
    'AFEAUQBRAFc/GZVprzl7uPjc7yxx8uolc9ls2WMtWWzZYNWWzZYP/9k=',
  ].join(``),
  [
    '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABh',
    'Y3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAAB',
    'UAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAA',
    'AAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9Y',
    'WVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAM',
    'ZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAwICQsJCAwLCgsODQwOEh4UEhEREiUbHBYe',
    'LCcuLisnKyoxN0Y7MTRCNCorPVM+QkhKTk9OLztWXFVMW0ZNTkv/2wBDAQ0ODhIQEiQUFCRLMisyS0tLS0tLS0tLS0tLS0tLS0tL',
    'S0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0v/wAARCADwAPADASIAAhEBAxEB/8QAGgABAQEBAQEBAAAAAAAAAAAAAAEC',
    'BAMFBv/EACkQAQEAAgECBQQCAwEAAAAAAAARAQIDBCESMUFxgTJCUWETkTNSsSL/xAAYAQEBAQEBAAAAAAAAAAAAAAAAAQIDBP/E',
    'ABkRAQEBAQEBAAAAAAAAAAAAAAABETECEv/aAAwDAQACEQMRAD8A/XUrNK8T0tUrNKDVKzSg1Ss0oNUrNKDVKzSg1Ss0oNUrNKDV',
    'KzSg1Ss0oNUrNKDVKzSg1Ss0oNUrNKDVKzSgglKgolKCiUoKJSgolKCiUoKJSgolKCiUoKJSgolKCiUoKJSgolKCiUoJSpSgtKlK',
    'C0qUoLSpSgtKlKC0qUoLSpSgtKlKC0qUoLSpSgtKlKC0qUoLSpSgtKlKC0qUoM0qALSoAtKgC0qALSoAtKgC0renFtt3z2w9teLT',
    'X0vuuGualdeMYx5YM4xnzxhflNclK6duLTPpPZ478W2vfHfCYusUqCC0qALSoAtKgC0qALSoAgyCtDIDQyA0MgNDIDT34eP7tse2',
    'HnwaeLa58sOlqRm1RBpFEAUQB5c3H92vzh4Oxzc+nh2uPLLNiysDIy00MgNDIDQyA0MgIIIKIAogCiAKIA7ODHh48fvu2mvbXGP0',
    'OjCiAKIAogCsc+PFx5/Xdo2765x+gcQg5tqIAogCiAKIAgyA0MgNDIDQyA0MgPoYzcYyPPg28XHj9dm3RhRAFEAUQBTOZjOUY59v',
    'Dx5/fYHKMjm20MgNDIDQyA0MgIIAogCiAKIAogD24OTwbzPll1vnOjg5sTGu2fbLUqWOkQaZUQBRAFcnPyePeY8sNc/NiZ11z75c',
    '7NrUiiDKqIAogCiAKIAlKyA1SsgNUrIDVKyA1SsgNUrID24+fbTtnvh0a8+m3rPdwiymPo42xnyzjPyZ2xjzzjHy+cL9Jju259Nf',
    'W+zn5Ofbftjth4iWrjVKyINUrIDVKyA1SsgNUrIDVKyAgggogCiAKIAogCiAKI1jTfPlrn+lEG/4eT/U/h5P9TKMC503x565/pkF',
    'EEFEAUQBRAFEAUQBKVKUVaVKUFpUpQWlSlBaVHRw9P68n9LJqPLTj23z/wCcfLo06bXH1Zvs9sTGJgakTTXTXX6dcYVBUUQBU201',
    '2+rXGQB479Nrn6Mz3c+/Htx/Vj5dxmZxMpYuvn0r35en9eP+nOzZirSpSoq0qUoLSpSgtKlKDIgCiAKIAojp6Xj+/b4WTR6cHD4M',
    'eLb6v+PdBthRAFEAUQBRAFEAV4c/D48eLX6v+vYB80dHVcf36/LmYsxtRBBRAFEAQZAaGQGhkBvTXx741x6vo4xjXGMY8sOTo9bt',
    'tt+Ozra8s1RBpFEAUQBRAFEAUQBRADOMbYzjPll87fXOm+dc+j6Lk6zWba7fnsz6WPAZGWmhkBoZAQQRVEAUQB3dHicV/OXu8el/',
    'wa/L1dJxiqIKiiAKIAogCiAKIAogCvDrMXiv4y9nl1X+Db4S8WOEQc21EAUQBBmlBoZpQaGaUHf0e14Z+MvdxdFvNttfz3djpOMV',
    'RBRRAFEAUQBRAFEAUQBXh1mZwz85ezj63e7a6/jul4R4DNK5ttDNKDQzSg//2Q==',
  ].join(``),
  [
    '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABh',
    'Y3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'AAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAAB',
    'UAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAA',
    'AAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9Y',
    'WVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAM',
    'ZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAwICQsJCAwLCgsODQwOEh4UEhEREiUbHBYe',
    'LCcuLisnKyoxN0Y7MTRCNCorPVM+QkhKTk9OLztWXFVMW0ZNTkv/2wBDAQ0ODhIQEiQUFCRLMisyS0tLS0tLS0tLS0tLS0tLS0tL',
    'S0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0v/wAARCADwAPADASIAAhEBAxEB/8QAGgABAQEBAQEBAAAAAAAAAAAAAAEC',
    'BAMFBv/EACsQAQEAAgECBAUEAwEAAAAAAAARAQIDBCESMVFxIjJBYYETI5GxM1KhQv/EABgBAQEBAQEAAAAAAAAAAAAAAAABAgME',
    '/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwD9PSpSvS7LSpSgtKlKC0qUoLSpSgtKlKC0qUoLSpSgtKlKC0qU',
    'oLSpSgtKlKC0qUoLSpSgtKlKCUrNKDVKzSg1Ss0oNUrNKDVKzSg1Ss0oNUrNKDVKzSg1Ss0oNUrNKDVKzSg1Ss0oNUrNKDVKzSg1',
    'Ss0oJSpSgtKlKC0qUoLSpSgtKlKC0qUoLSpSgtKlKC0qUoLSpSgtKlKC0qUoLSpSgtKlKC0qUoM0qUoLSpSgtKlKC0qUoLSpSgtK',
    'lKC0r04+Hbbvnth7a8Omv0vuajlpXbjGMeWMGcYz54wmmuKldW3Dpt9J7PHk4dte+O+F0edKlKKtKlKC0qUoLSpSgtKlKC0qUoJS',
    's0oNUrNKDVKzSg1Ss0oNUrNKDVdHBxdsbbY9sPLp9PHvc+WHXUqVRKVEUSlBRKUHjz8Xbxa498Oeu5ydRp4N7jyysWMUrNKqtUrN',
    'KDVKzSg1Ss0oNUrNKCUqUqi0qUoLSpSgtKlKC0qUoO3p9fDxY+/d6sa9tcY9MLWGWhmlBoZpQaGaUGnl1Gvi4s/bu3U2765x9gcN',
    'KlK20tKlKC0qUoLSpSgtKlKDNKlKC0qUoLSpSgtKlKC0qUoPpa5uuM/ZXj0+/i4sfbs9Kwy0M0oNDNKDQzSg0m2ZrnP2SvPqN/Dx',
    'Z+/YHHSpSttLSpSgtKlKC0qUoLSpSgggCiAKIAogCiAPbp+TwbzPll2Pmunp+fExrvn2yliV1DKsoogCiICuPqOTx7zHlhvn58TO',
    'mmffLmakWKIKqiAKIAogCiAIM0oNDNKDQzSg0M0oNDNKDQzSg9+LqNtO2fiw6Neo49vrPdwUphj6eNtc+WcZ/JnbXHnnGPy+ZSpi',
    'Y79uo49frfZz8nUbb9sfDh4Uq4uNDNKDQzSg0M0oNDNKDQzSg0M0oJSpSgtKlKC0qUoLSpSgtKlKC0qUoLSo1jj3z5a5/gEpW/0O',
    'X/X/AKfocv8Ar/0GKVc8e+vnrn+GQWlSlBaVKUFpUpQWlSlBaVKUFpUpQZpUpVFpUpQWlSlBaVKUFpUdXD03ltyfwg8ePj35M/Dj',
    '8unTpdcfPm+z3xMYmO2BNTU1010+XXGGkERRAFZ2012+bXGVAeG/S65+TM+2XNyce/Hn4sfl9AzM4mfJdXXzKV083Tf+uP8Ahyqq',
    '0qUqi0qUoLSpSgtKlKCUrNKDVKzSg1Ss0oNUZrq6Tiv7m2PYHr0/B4MeLb5v6e6DDKiAKIAogCiAKIArw6jg8ePFr839vYB8wro6',
    'vin7muPdy1tpqlZpQapWaUGqVmlBKVKUFpUpQWlSlBvj1zvvjXH1y+lrjGuMYx5YcfQ63bbb0xHYzUqiCIogCiAKIAogCiAKIAbY',
    'xtjOM+WXzeTXOm+dc/TL6Tj67Wba7evZYsc9KlK0q0qUoLSpSgzSpSgtKlKC0qUoPodFicN9cvd4dJ/g1/P9vZmoogiKIAogCiAK',
    'IAogCiAK8OtxeG+mXs8er/wbfj+1iuClSlaVaVKUFpUpQSlZpVGqVmlBqlZpQfR6La8M9MvdxdBvNttfXFdrFQAEAAAAAAAAAAAA',
    'Hh1u04Z65e7i6/e7a6+mLkiualZpW1apWaUGqVmlB//Z',
  ].join(``),
];

// Pilih gambar secara tetap berdasarkan id pegawai, supaya satu pegawai
// selalu tampil dengan warna yang sama di seluruh galeri.
function gambarContoh(userId) {
  return Buffer.from(GAMBAR[userId % GAMBAR.length], 'base64');
}

module.exports = { gambarContoh, jumlahVarian: GAMBAR.length };
